### ISSUE TITLE
websocket如何验证token？

### ISSUE THREAD

**Issue by lwhua** [usthe/sureness#70]
我想通过sureness验证websocket的token，token在头部传输，运行了演示项目，没明白怎么验证websocket的token，和验证rest接口是一样的吗？

**Comment by tomsun28** [comment]
js 目前无法在websocket新建阶段将token塞入头，建议处理方式是将token作为参数传入:    
``` new WebSocket("ws://localhost:8088/webSocket/demo?token=jwtValue");  ```     
websocket新建阶段其实是http请求，所以可以像rest接口一样进行认证鉴权，需要自定义subjectCreator去上面格式的请求参数取jwt，我已经写好了对应的subjectCreator，更新最新代码即可参照使用，这个特性也会合入在下一个版本发布

**Comment by tomsun28** [comment]
hi 有兴趣对sureness使用者登记么 https://github.com/usthe/sureness/issues/64
