### ISSUE TITLE
no security module in sureness-core the latest version

### ISSUE THREAD

**Issue by ZarkMedo** [usthe/sureness#75]
import com.usthe.sureness.security.XssSqlServletRequestWrapper; not found,

**Comment by tomsun28** [comment]
Would you like to take some time to remove xss code in [sample-bootstrap](https://github.com/tomsun28/sureness/blob/master/sample-bootstrap/src/main/java/com/usthe/sureness/sample/bootstrap/SurenessFilterExample.java). It should be used after next version publish. sureness welcomes contributor pr. 😀😀

**Comment by tomsun28** [comment]
thanks for this issue, i have revert near commit to fix it
