### ISSUE TITLE
对于DELETE请求会提示“Invalid CORS request”

### ISSUE THREAD

**Issue by lwhua** [usthe/sureness#80]
添加了sureness后，通过jquery发送delete请求会提示“Invalid CORS request”，通过curl命令发送delete请求也正常，get和post请求正常，spring boot 已经配置跨域，请问是不是sureness导致的？

**Comment by tomsun28** [comment]
这是跨域问题，sureness不会返回这个，按道理不会是sureness造成 你可以在filter入口debug下呢

跨域问题一般解决方式，后端添加支持跨域即可 [之前的代码，应该还能用](https://github.com/tomsun28/bootshiro/blob/master/src/main/java/com/usthe/tom/config/SecurityCorsConfiguration.java)

**Comment by lwhua** [comment]
> 这是跨域问题，sureness不会返回这个，按道理不会是sureness造成 你可以在filter入口debug下呢
> 
> 跨域问题一般解决方式，后端添加支持跨域即可 [之前的代码，应该还能用](https://github.com/tomsun28/bootshiro/blob/master/src/main/java/com/usthe/tom/config/SecurityCorsConfiguration.java)

filter入口有接收到请求，就唯独delete请求不行，请求是通过Nginx代理到后端服务

**Comment by tomsun28** [comment]
试试将sureness相关的那个filter禁用来排除，curl是好的那就是jquery的跨域问题了。用jquery调用后台有啥报错么，建议对比不同方式下请求头和响应头有啥区别  不介意的话帖一波我也看看
